### ISSUE TITLE
Segmentation DICOM plugin does not load

### ISSUE THREAD

**Issue by fedorov** [fedorov/Reporting#48]
testing with April 9 nightly, the plugin fails to load with the following:

```
 File "/Applications/Slicer-4.4.0-2015-04-09/Slicer.app/Contents/Extensions-24167/Reporting/lib/Slicer-4.4/qt-scripted-modules/DICOMSegmentationPlugin.py", line 15, in <module>
    class DICOMSegmentationPluginClass(DICOMPlugin):
NameError: name 'DICOMPlugin' is not defined
```

@naucoin can you investigate?

There were no changes to the plugin, and DICOMPlugin is imported from DICOMLib

**Comment by naucoin** [comment]
I had noticed that in some of the tests and thought I'd found a work around but I wasn't seeing it in my dev version. I rebuilt Reporting this morning from scratch and the plug in isn't loading with the same error, so I can dig into it more now.

**Comment by pieper** [comment]
Hola! - I'll bet this is related to the recent changes by @jcfr regarding
python namespaces.

**Comment by naucoin** [comment]
@pieper thanks for the tip!

**Comment by jcfr** [comment]
The problem is here: https://github.com/fedorov/Reporting/blob/e787f9ba83432b45578595e8720baf48c746c32d/Py/DICOMSegmentationPlugin.py#L6-L15

You are basically importing `DICOMLib` but using directly `DICOMPlugin`.

As done in [1], change

```
import DICOMLib
```

with 

```
from DICOMLib import DICOMPlugin
```


For sake of consistency, you could also add 

```
from DICOMLib import DICOMLoadable
```

and change

`DICOMLib.DICOMLoadable` into `DICOMLoadable`

Hth
Jc

[1] https://github.com/Slicer/Slicer/blob/9ce34175d2684ffc567d14e9da14aafefe5f20f7/Modules/Scripted/DICOMPlugins/DICOMSlicerDataBundlePlugin.py#L3

**Comment by naucoin** [comment]
Thanks, I had just made that change and was testing it, seems good so I'll get it uploaded.

**Comment by naucoin** [comment]
Pull request for extensions index:
https://github.com/Slicer/ExtensionsIndex/pull/941
